name: Bug Report
description: File a bug report (software did not work as expected)
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - aolney
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please only use this bug report for software-related errors, not for typos, broken links, etc.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: platforms
    attributes:
      label: What platforms are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - OSX
        - Android
        - iOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
