name: Correction
description: Propose a correction
title: "[Correction]: "
labels: ["correction", "triage"]
assignees:
  - aolney
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a correction! Please only use this form for corrections like typos, broken links, or factual errors. Please use other forms for reporting bugs or making suggestions.
  - type: textarea
    id: what-happened
    attributes:
      label: What is the material in question?
      description: Also tell us, what did you propose as a correction?
      placeholder: Tell us what you see!
      value: "Whoopsie!"
    validations:
      required: true
